// Package reconcile implements the `carl reconcile` command.
// It updates repository-specific memory sections in .github/carl/memory.md
// using data from .github/carl/repo-map.json, preserving human-authored content.
package reconcile

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/goldjg/carl/internal/repomap"
)

// MemoryFile is the path of memory.md relative to the repository root.
const MemoryFile = ".github/carl/memory.md"

// genBeginMarker and genEndMarker delimit the generated section in memory.md.
// Content between these markers is owned by `carl reconcile` and will be
// overwritten on each run. Do not place human-authored content inside them.
const (
	genBeginMarker = "<!-- BEGIN GENERATED: reconcile -->"
	genEndMarker   = "<!-- END GENERATED: reconcile -->"
)

// Command implements `carl reconcile`.
type Command struct{}

// New returns a new reconcile Command.
func New() *Command { return &Command{} }

// Name returns the command name.
func (c *Command) Name() string { return "reconcile" }

// Synopsis returns a short description.
func (c *Command) Synopsis() string {
	return "Update repository-specific memory sections from current repo-map data"
}

// Run executes `carl reconcile` in the current working directory.
func (c *Command) Run(_ context.Context, _ []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("get working directory: %w", err)
	}
	return c.RunInDir(cwd)
}

// RunInDir executes the reconcile logic rooted at rootDir.
// Exported for testing without changing the process working directory.
func (c *Command) RunInDir(rootDir string) error {
	// Verify repo-map.json exists.
	mapPath := filepath.Join(rootDir, filepath.FromSlash(repomap.OutputFile))
	mapData, err := os.ReadFile(mapPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("repo map not found — run `carl map` first")
		}
		return fmt.Errorf("read repo map: %w", err)
	}

	// Verify memory.md exists.
	memPath := filepath.Join(rootDir, filepath.FromSlash(MemoryFile))
	memData, err := os.ReadFile(memPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("memory.md not found — run `carl init` first")
		}
		return fmt.Errorf("read memory.md: %w", err)
	}

	// Parse repo map.
	var m repomap.Map
	if err := json.Unmarshal(mapData, &m); err != nil {
		return fmt.Errorf("parse repo map: %w", err)
	}

	// Validate that any existing generated-section markers are well-formed.
	if err := checkMarkers(string(memData)); err != nil {
		return err
	}

	// Build and inject the generated section.
	generated := buildGeneratedSection(&m)
	newContent, changed := injectSection(string(memData), generated)

	if !changed {
		fmt.Println("No reconciliation needed.")
		return nil
	}

	if err := os.WriteFile(memPath, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write memory.md: %w", err)
	}

	fmt.Println("Reconciled durable artefacts.")
	fmt.Printf("  %s\n", MemoryFile)
	return nil
}

// buildGeneratedSection produces the full generated block including its markers.
// The block opens with genBeginMarker and closes with genEndMarker, each on
// their own line. A trailing newline is always appended after genEndMarker.
func buildGeneratedSection(m *repomap.Map) string {
	var b strings.Builder

	b.WriteString(genBeginMarker + "\n")
	b.WriteString("## Repository snapshot\n\n")
	b.WriteString("This section is regenerated by `carl reconcile`. Do not edit manually.\n\n")

	if len(m.Languages) > 0 {
		b.WriteString("**Languages:** " + strings.Join(m.Languages, ", ") + "  \n")
	}
	b.WriteString("**Last reconciled:** " + time.Now().UTC().Format("2006-01-02") + "\n")

	if len(m.EntryPoints) > 0 {
		b.WriteString("\n### Entry points\n\n")
		for _, ep := range m.EntryPoints {
			if ep.Purpose != "" {
				b.WriteString(fmt.Sprintf("- `%s` — %s\n", ep.Path, ep.Purpose))
			} else {
				b.WriteString(fmt.Sprintf("- `%s`\n", ep.Path))
			}
		}
	}

	if len(m.Directories) > 0 {
		b.WriteString("\n### Key directories\n\n")
		keys := make([]string, 0, len(m.Directories))
		for k := range m.Directories {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := m.Directories[k]
			if v != "" {
				b.WriteString(fmt.Sprintf("- `%s` — %s\n", k, v))
			} else {
				b.WriteString(fmt.Sprintf("- `%s`\n", k))
			}
		}
	}

	if len(m.Workflows) > 0 {
		b.WriteString("\n### Workflows\n\n")
		for _, wf := range m.Workflows {
			if wf.Purpose != "" {
				b.WriteString(fmt.Sprintf("- `%s` — %s\n", wf.Path, wf.Purpose))
			} else {
				b.WriteString(fmt.Sprintf("- `%s`\n", wf.Path))
			}
		}
	}

	if len(m.Governance) > 0 {
		b.WriteString("\n### Governance artefacts\n\n")
		for _, g := range m.Governance {
			if g.Purpose != "" {
				b.WriteString(fmt.Sprintf("- `%s` — %s\n", g.Path, g.Purpose))
			} else {
				b.WriteString(fmt.Sprintf("- `%s`\n", g.Path))
			}
		}
	}

	if len(m.Documentation) > 0 {
		b.WriteString("\n### Documentation\n\n")
		for _, d := range m.Documentation {
			if d.Purpose != "" {
				b.WriteString(fmt.Sprintf("- `%s` — %s\n", d.Path, d.Purpose))
			} else {
				b.WriteString(fmt.Sprintf("- `%s`\n", d.Path))
			}
		}
	}

	b.WriteString(genEndMarker + "\n")
	return b.String()
}

// checkMarkers returns an error when the generated-section markers in content
// are in a malformed state:
//   - begin marker present but end marker absent
//   - end marker present but begin marker absent
//   - end marker appears before begin marker
//
// In any of these cases the caller should not write anything; the user must
// repair memory.md manually or re-run from a clean file.
func checkMarkers(content string) error {
	beginIdx := strings.Index(content, genBeginMarker)
	endIdx := strings.Index(content, genEndMarker)
	hasBegin := beginIdx >= 0
	hasEnd := endIdx >= 0

	const advice = "repair the markers manually or re-run `carl reconcile` from a clean memory.md"

	switch {
	case hasBegin && !hasEnd:
		return fmt.Errorf("memory.md contains %q but is missing %q — "+
			"the generated section markers are malformed; %s",
			genBeginMarker, genEndMarker, advice)
	case hasEnd && !hasBegin:
		return fmt.Errorf("memory.md contains %q but is missing %q — "+
			"the generated section markers are malformed; %s",
			genEndMarker, genBeginMarker, advice)
	case hasBegin && hasEnd && endIdx < beginIdx:
		return fmt.Errorf("memory.md has the end marker appearing before the begin marker — "+
			"the generated section markers are malformed; %s", advice)
	}
	return nil
}

// injectSection inserts or replaces the generated section in memoryContent.
// It returns the updated content and a boolean indicating whether the content
// changed.
//
// Replacement: if both genBeginMarker and genEndMarker are already present,
// the entire span (including markers and the trailing newline) is replaced with
// generatedSection. If the span is byte-identical to generatedSection, the
// content is unchanged and changed=false is returned.
//
// Insertion: if no markers exist, generatedSection is inserted before the last
// "## Last updated" heading (preceded by a blank line) so the human-authored
// last-updated note stays at the end. If no such heading exists, generatedSection
// is appended after a blank line at the end of the file.
func injectSection(memoryContent, generatedSection string) (string, bool) {
	beginIdx := strings.Index(memoryContent, genBeginMarker)
	endIdx := strings.Index(memoryContent, genEndMarker)

	if beginIdx >= 0 && endIdx > beginIdx {
		// Compute end of existing span (inclusive of the trailing newline).
		endOfEnd := endIdx + len(genEndMarker)
		if endOfEnd < len(memoryContent) && memoryContent[endOfEnd] == '\n' {
			endOfEnd++
		}
		existing := memoryContent[beginIdx:endOfEnd]
		if existing == generatedSection {
			return memoryContent, false
		}
		return memoryContent[:beginIdx] + generatedSection + memoryContent[endOfEnd:], true
	}

	// No existing generated section — insert before "## Last updated" or at end.
	const lastUpdatedHeader = "\n## Last updated"
	if insertIdx := strings.LastIndex(memoryContent, lastUpdatedHeader); insertIdx >= 0 {
		return memoryContent[:insertIdx] + "\n" + generatedSection + memoryContent[insertIdx:], true
	}

	// Fallback: append at end, ensuring a blank-line separator.
	if !strings.HasSuffix(memoryContent, "\n\n") {
		if strings.HasSuffix(memoryContent, "\n") {
			return memoryContent + "\n" + generatedSection, true
		}
		return memoryContent + "\n\n" + generatedSection, true
	}
	return memoryContent + generatedSection, true
}
